Expose "setOffline" method
amplitude/Amplitude-Flutter pull request #136
Opened 2023-01-16 17:20 UTC by bonnyfone

#81

2023-04-04 12:37 UTC, piotrpachalko commented
@yuhao900914 what do we do to have this PR approved?

2023-04-04 16:32 UTC, yuhao900914 commented
Hi @bonnyfone, thanks for choosing Amplitude and contributing to Amplitude. 
Amplitude-Flutter right now also has web support. So when you add a function, you need to add it on Android, iOS, and also the Web. 
There are 2 places we need to change to make web support not throwing error
1. [lib/web/amplitude_js.dart](https://github.com/amplitude/Amplitude-Flutter/blob/main/lib/web/amplitude_js.dart) -> the function signature
2. [lib/amplitude_web.dart ](https://github.com/amplitude/Amplitude-Flutter/blob/main/lib/amplitude_web.dart)-> the bridge between flutter and Amplitude-JavaScript. We need to return `false` here since flutter web didn't support `setOffline`.

Thanks.

2023-04-04 16:33 UTC, yuhao900914 requested changes
Please also make the change on the Flutter web, otherwise it's going to throw error on Flutter web.

2023-04-18 08:37 UTC, nishiths23 commented
Added suggested changes in this pull request

2023-06-26 08:35 UTC, piotrpachalko commented
Hi @yuhao900914, the changes you've requested for the Amplitude-Flutter have been submitted at PR #142. Please proceed.

2023-07-24 23:21 UTC, closed without merging